services:
  nginx:
    image: alfg/nginx-rtmp
    container_name: nginx-rtmp
    ports:
      - "1935:1935"
      - "8081:80"
    volumes:
      - ./.dockerfiles/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.dockerfiles/hls:/tmp/hls
      - ./.dockerfiles/record:/tmp/record
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: livestream
      MYSQL_USER: streamer
      MYSQL_PASSWORD: streamerpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  php:
    build:
      context: .
      dockerfile: .dockerfiles/php/Dockerfile
    container_name: php-backend
    volumes:
      - .:/var/www/html
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - mysql


volumes:
  mysql_data:
